#!/bin/sh

# stash any unstaged changes
STASH_NAME=pre-commit-$(date +%s)
git stash save -q --keep-index $STASH_NAME

# perform gradle tests
./gradlew check
RESULT=$?

# Unstash 
git stash pop -q stash@{$STASH_NAME}


# If gradle tests failed, exit with error code
if [ $RESULT -ne 0 ]; then
    exit $RESULT
fi

