on: [push, pull_request]
jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  gradle-check:
    # Name the Job
    name: Run Gradle Checks
    # Set the type of machine to run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: zulu
        java-package: jdk+fx
    - name: Run headless test
      uses: GabrielBB/xvfb-action@v1
      with:
        run: ./gradlew check
